export ZSH="$HOME/.oh-my-zsh"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

ZSH_THEME="robbyrussell"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

plugins=(zsh-interactive-cd history-substring-search zsh-autosuggestions zsh-syntax-highlighting git)

source $ZSH/oh-my-zsh.sh
source <(/usr/bin/starship init zsh --print-full-init)

if [ -f $HOME/cargo.env ] ; then
  source $HOME/.cargo/env
fi

export FZF_ALT_C_COMMAND="fd --type d --strip-cwd-prefix --exclude .git ."
export FZF_CTRL_T_COMMAND="fd --type f --strip-cwd-prefix --exclude .git ."

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

export EDITOR=nvim
alias cat="bat"
alias ls="exa --icons"
alias vi="nvim"
alias vim="nvim"
alias pacman="sudo pacman"
alias zedit="cd ~/.dotfiles ; nvim"
alias zlocal="nvim ~/.zshrc.local"
alias ssh="kitty +kitten ssh"
alias interno="ssh -p 4522 root@minhacasa.e01aio.com.br"
alias servidor8="ssh root@servidor8.usign.io"
alias servidor9="ssh root@servidor9.usign.io"
alias servidor10="ssh root@servidor10.usign.io"
alias servidor11="ssh root@servidor11.usign.io"
alias servidor12="ssh root@servidor12.usign.io"
alias servidor13="ssh root@servidor13.usign.io"
alias servidor14="ssh root@servidor14.usign.io"
alias servidor15="ssh root@servidor15.usign.io"
alias servidor16="ssh root@servidor16.usign.io"
alias servidor17="ssh root@servidor17.usign.io"
alias vtruqa="ssh root@server-qa.vtru.dev"
alias vtruproduction="ssh root@studio-server-production.vitruveo.xyz"
alias proxy1="ssh root@proxy1.jbtec.com.br"
alias zabbix="ssh root@zabbix.jbtec.com.br"

alias i3config="nvim ~/.config/i3/config"
export PATH="$PATH:$HOME/.dotfiles/scripts:$HOME/.local/bin:$HOME/cargo/bin"


# bun completions
[ -s "/home/nsfilho/.bun/_bun" ] && source "/home/nsfilho/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

if [ -f $HOME/.zshrc.local ] ; then
  source $HOME/.zshrc.local
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
